#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : acrn-devicemodel
Version  : 1.0
Release  : 4
URL      : https://github.com/projectacrn/acrn-devicemodel/archive/v1.0.tar.gz
Source0  : https://github.com/projectacrn/acrn-devicemodel/archive/v1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: acrn-devicemodel-bin
Requires: acrn-devicemodel-data
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(uuid)
BuildRequires : zlib-dev

%description
BUILD DEPENDANCE
for CentOS
yum install libuuid-devel
BUILD
make
CLEAN
make clean

%package bin
Summary: bin components for the acrn-devicemodel package.
Group: Binaries
Requires: acrn-devicemodel-data

%description bin
bin components for the acrn-devicemodel package.


%package data
Summary: data components for the acrn-devicemodel package.
Group: Data

%description data
data components for the acrn-devicemodel package.


%prep
%setup -q -n acrn-devicemodel-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520523225
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1520523225
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/acrn-dm

%files data
%defattr(-,root,root,-)
/usr/share/acrn/demo/bridge.sh
/usr/share/acrn/demo/launch_uos.sh
