#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : acrn-devicemodel
Version  : 0.1.rc2
Release  : 5
URL      : https://github.com/projectacrn/acrn-devicemodel/archive/v0.1-rc2.tar.gz
Source0  : https://github.com/projectacrn/acrn-devicemodel/archive/v0.1-rc2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: acrn-devicemodel-bin
Requires: acrn-devicemodel-data
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(uuid)
BuildRequires : zlib-dev

%description
ACRN Device Model
#################
Introduction
============
The ACRN Device Model provides **device sharing** capabilities between the Service OS and Guest OSs. It is a component that is used in conjunction with the `ACRN Hypervisor`_ and this is installed within the Service OS. You can find out more about Project ACRN on the `Project ACRN documentation`_ website.

%package bin
Summary: bin components for the acrn-devicemodel package.
Group: Binaries
Requires: acrn-devicemodel-data

%description bin
bin components for the acrn-devicemodel package.


%package data
Summary: data components for the acrn-devicemodel package.
Group: Data

%description data
data components for the acrn-devicemodel package.


%prep
%setup -q -n acrn-devicemodel-0.1-rc2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520603038
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1520603038
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/acrn-dm

%files data
%defattr(-,root,root,-)
/usr/share/acrn/demo/bridge.sh
/usr/share/acrn/demo/launch_uos.sh
